name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add known hosts
        run: |
          ssh-keyscan -H 13.48.99.179 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp -r ./* ec2-user@13.48.99.179>:/app/my-app
          ssh ec2-user@13.48.99.179> << 'EOF'
          cd /app/my-app
          # Run deployment commands (e.g., npm install, systemctl restart service)
          EOF